"""initial schema

Revision ID: 28376b48e201
Revises:
Create Date: 2026-08-06 15:47:40.707420
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "28376b48e201"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artifacts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("path", sa.String(length=512), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("media_type", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("retention_policy", sa.String(length=32), nullable=False),
        sa.Column("created_at_utc", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("path"),
    )
    op.create_table(
        "bot_targets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("galaxy", sa.Integer(), nullable=False),
        sa.Column("system", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("is_bot", sa.Boolean(), nullable=False),
        sa.Column("latest_owner_name", sa.String(length=64), nullable=True),
        sa.Column("last_scanned_at_utc", sa.DateTime(), nullable=True),
        sa.Column("last_attack_at_utc", sa.DateTime(), nullable=True),
        sa.Column("last_dispatch_at_utc", sa.DateTime(), nullable=True),
        sa.Column("last_report_at_utc", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("galaxy", "system", "position", name="uq_bot_targets_coordinate"),
    )
    op.create_table(
        "scan_plans",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("time_window_start", sa.String(length=5), nullable=False),
        sa.Column("time_window_end", sa.String(length=5), nullable=False),
        sa.Column("timezone_name", sa.String(length=64), nullable=False),
        sa.Column("dry_run", sa.Boolean(), nullable=False),
        sa.Column("created_at_utc", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "state_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("aggregate_type", sa.String(length=32), nullable=False),
        sa.Column("aggregate_id", sa.Uuid(), nullable=False),
        sa.Column("event", sa.String(length=64), nullable=False),
        sa.Column("before_state", sa.String(length=32), nullable=True),
        sa.Column("after_state", sa.String(length=32), nullable=True),
        sa.Column("occurred_at_utc", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_state_events_aggregate",
        "state_events",
        ["aggregate_type", "aggregate_id"],
        unique=False,
    )
    op.create_table(
        "target_revisits",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=False),
        sa.Column("target_galaxy", sa.Integer(), nullable=True),
        sa.Column("target_system", sa.Integer(), nullable=True),
        sa.Column("target_position", sa.Integer(), nullable=True),
        sa.Column("requested_at_utc", sa.DateTime(), nullable=False),
        sa.Column("executed_at_utc", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ui_observations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("screen", sa.String(length=32), nullable=False),
        sa.Column("ui_version", sa.String(length=64), nullable=True),
        sa.Column("detection_result", sa.String(length=255), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("evidence_artifact_id", sa.Uuid(), nullable=True),
        sa.Column("observed_at_utc", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "run_instances",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("target_date", sa.DateTime(), nullable=True),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("cursor_galaxy", sa.Integer(), nullable=True),
        sa.Column("cursor_system", sa.Integer(), nullable=True),
        sa.Column("cursor_position", sa.Integer(), nullable=True),
        sa.Column("started_at_utc", sa.DateTime(), nullable=True),
        sa.Column("drained_at_utc", sa.DateTime(), nullable=True),
        sa.Column("finished_at_utc", sa.DateTime(), nullable=True),
        sa.Column("created_at_utc", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["scan_plans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(op.f("ix_run_instances_plan_id"), "run_instances", ["plan_id"], unique=False)
    op.create_table(
        "scan_ranges",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("start_galaxy", sa.Integer(), nullable=False),
        sa.Column("start_system", sa.Integer(), nullable=False),
        sa.Column("start_position", sa.Integer(), nullable=False),
        sa.Column("end_galaxy", sa.Integer(), nullable=False),
        sa.Column("end_system", sa.Integer(), nullable=False),
        sa.Column("end_position", sa.Integer(), nullable=False),
        sa.Column("origin_galaxy", sa.Integer(), nullable=False),
        sa.Column("origin_system", sa.Integer(), nullable=False),
        sa.Column("origin_position", sa.Integer(), nullable=False),
        sa.Column("fleet_preset_name", sa.String(length=120), nullable=False),
        sa.Column("fleet_preset_signature", sa.String(length=255), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["scan_plans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scan_ranges_plan_id"), "scan_ranges", ["plan_id"], unique=False)
    op.create_table(
        "attack_intents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("origin_galaxy", sa.Integer(), nullable=False),
        sa.Column("origin_system", sa.Integer(), nullable=False),
        sa.Column("origin_position", sa.Integer(), nullable=False),
        sa.Column("target_galaxy", sa.Integer(), nullable=False),
        sa.Column("target_system", sa.Integer(), nullable=False),
        sa.Column("target_position", sa.Integer(), nullable=False),
        sa.Column("preset_name", sa.String(length=120), nullable=False),
        sa.Column("preset_signature", sa.String(length=255), nullable=False),
        sa.Column("cycle_start_utc", sa.DateTime(), nullable=False),
        sa.Column("guard_status", sa.String(length=32), nullable=False),
        sa.Column("forced_revisit", sa.Boolean(), nullable=False),
        sa.Column("created_at_utc", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run_instances.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "run_id",
            "target_galaxy",
            "target_system",
            "target_position",
            "cycle_start_utc",
            "forced_revisit",
            name="uq_attack_intent_run_target_cycle",
        ),
    )
    op.create_index(op.f("ix_attack_intents_run_id"), "attack_intents", ["run_id"], unique=False)
    op.create_table(
        "coordinate_scans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("galaxy", sa.Integer(), nullable=False),
        sa.Column("system", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("scanned_at_utc", sa.DateTime(), nullable=False),
        sa.Column("owner_name", sa.String(length=64), nullable=True),
        sa.Column("is_bot", sa.Boolean(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("evidence_artifact_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run_instances.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_coordinate_scans_run_id"), "coordinate_scans", ["run_id"], unique=False
    )
    op.create_table(
        "attack_dispatches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("intent_id", sa.Uuid(), nullable=False),
        sa.Column("dispatched_at_utc", sa.DateTime(), nullable=False),
        sa.Column("dry_run", sa.Boolean(), nullable=False),
        sa.Column("accepted", sa.Boolean(), nullable=False),
        sa.Column("evidence_artifact_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["intent_id"],
            ["attack_intents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("intent_id"),
    )
    op.create_table(
        "battle_reports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("reported_at_utc", sa.DateTime(), nullable=False),
        sa.Column("raw_time_text", sa.String(length=64), nullable=True),
        sa.Column("attacker_origin_galaxy", sa.Integer(), nullable=False),
        sa.Column("attacker_origin_system", sa.Integer(), nullable=False),
        sa.Column("attacker_origin_position", sa.Integer(), nullable=False),
        sa.Column("defender_target_galaxy", sa.Integer(), nullable=False),
        sa.Column("defender_target_system", sa.Integer(), nullable=False),
        sa.Column("defender_target_position", sa.Integer(), nullable=False),
        sa.Column("match_status", sa.String(length=16), nullable=False),
        sa.Column("match_confidence", sa.Float(), nullable=False),
        sa.Column("manual_review_status", sa.String(length=16), nullable=False),
        sa.Column("is_from_revisit", sa.Boolean(), nullable=False),
        sa.Column("ui_version", sa.String(length=64), nullable=True),
        sa.Column("dispatch_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["dispatch_id"],
            ["attack_dispatches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dispatch_id"),
    )
    op.create_table(
        "fleet_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column("side", sa.String(length=16), nullable=False),
        sa.Column("ship_type", sa.String(length=64), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("round_no", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["battle_reports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_fleet_snapshots_report_id"), "fleet_snapshots", ["report_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_fleet_snapshots_report_id"), table_name="fleet_snapshots")
    op.drop_table("fleet_snapshots")
    op.drop_table("battle_reports")
    op.drop_table("attack_dispatches")
    op.drop_index(op.f("ix_coordinate_scans_run_id"), table_name="coordinate_scans")
    op.drop_table("coordinate_scans")
    op.drop_index(op.f("ix_attack_intents_run_id"), table_name="attack_intents")
    op.drop_table("attack_intents")
    op.drop_index(op.f("ix_scan_ranges_plan_id"), table_name="scan_ranges")
    op.drop_table("scan_ranges")
    op.drop_index(op.f("ix_run_instances_plan_id"), table_name="run_instances")
    op.drop_table("run_instances")
    op.drop_table("ui_observations")
    op.drop_table("target_revisits")
    op.drop_index("ix_state_events_aggregate", table_name="state_events")
    op.drop_table("state_events")
    op.drop_table("scan_plans")
    op.drop_table("bot_targets")
    op.drop_table("artifacts")
    # ### end Alembic commands ###
